CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL UNIQUE,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (role IN ('STUDENT', 'MENTOR', 'ADMIN'))
);

CREATE TABLE student_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL,
    user_id bigint NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE stacks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description character varying(255),
    name character varying(255) NOT NULL UNIQUE
);

CREATE TABLE mentor_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    average_rating double precision NOT NULL,
    bio text,
    hourly_rate numeric(38,2),
    is_verified boolean NOT NULL,
    name character varying(255) NOT NULL,
    stack_id bigint,
    title character varying(255),
    user_id bigint NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE domain_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(255) NOT NULL UNIQUE,
    password_hash character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT domain_users_role_check CHECK (role IN ('STUDENT', 'MENTOR', 'ADMIN'))
);

CREATE TABLE domain_mentor_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    available boolean NOT NULL,
    bio character varying(255),
    display_name character varying(255),
    hourly_rate numeric(38,2),
    rating double precision,
    title character varying(255),
    stack_id bigint REFERENCES stacks(id),
    user_id bigint UNIQUE REFERENCES domain_users(id)
);

CREATE TABLE domain_student_profiles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name character varying(255),
    user_id bigint UNIQUE REFERENCES domain_users(id)
);

CREATE TABLE review_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description character varying(2000) NOT NULL,
    end_time timestamp(6) without time zone NOT NULL,
    evaluation_notes character varying(2000),
    start_time timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    mentor_id bigint NOT NULL REFERENCES domain_mentor_profiles(id),
    student_id bigint NOT NULL REFERENCES domain_student_profiles(id),
    CONSTRAINT review_sessions_status_check CHECK (status IN ('SCHEDULED', 'COMPLETED', 'CANCELED'))
);

CREATE TABLE mentor_availability (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week character varying(255) NOT NULL,
    end_time time(6) without time zone NOT NULL,
    start_time time(6) without time zone NOT NULL,
    mentor_id bigint NOT NULL REFERENCES domain_mentor_profiles(id),
    CONSTRAINT mentor_availability_day_of_week_check CHECK (day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'))
);

CREATE TABLE session_audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    confidence_score double precision,
    error_message character varying(2000),
    latency_ms bigint,
    predicted_tag character varying(255),
    status character varying(255) NOT NULL,
    session_id bigint NOT NULL UNIQUE REFERENCES review_sessions(id),
    CONSTRAINT session_audit_logs_status_check CHECK (status IN ('SUCCESS', 'FAILED'))
);

CREATE UNIQUE INDEX uq_mentor_slot ON review_sessions (mentor_id, start_time) WHERE (status = 'SCHEDULED');
